- .travis.yml
after_success:
- mvn clean test jacoco:report coveralls:report
> add JaCoCo report for Coveralls

- checkstyle_config.xml
- mentionserver/src/main/java/com.mention/SpringBootConfiguration.java
- mentionserver/src/main/java/com.mention/controller/PostController.java
- mentionserver/src/main/java/com.mention/controller/UserController.java
- mentionserver/src/main/java/com.mention/dao/PostDaoImpl.java
- mentionserver/src/main/java/com.mention/model/Message.java
- mentionserver/src/main/java/com.mention/model/Post.java
- mentionserver/src/main/java/com.mention/model/User.java
- mentionserver/src/main/java/com.mention/service/PostService.java
- mentionserver/src/main/java/com.mention/service/PostServiceImpl.java
- mentionserver/src/main/java/com.mention/service/UserServiceImpl.java
- pom.xml
Added Message entity with all necessary fields. Also added corresponding fields to User entity. Added nullable=false property to Post column USER_ID.  Also added lombok dependency to pom.xml to use later.
> Added Message entity with all joins

- checkstyle_config.xml
- mentionserver/src/main/java/com.mention/SpringBootConfiguration.java
- mentionserver/src/main/java/com.mention/controller/PostController.java
- mentionserver/src/main/java/com.mention/controller/UserController.java
- mentionserver/src/main/java/com.mention/dao/PostDaoImpl.java
- mentionserver/src/main/java/com.mention/model/Message.java
- mentionserver/src/main/java/com.mention/model/Post.java
- mentionserver/src/main/java/com.mention/model/User.java
- mentionserver/src/main/java/com.mention/service/PostService.java
- mentionserver/src/main/java/com.mention/service/PostServiceImpl.java
- mentionserver/src/main/java/com.mention/service/UserServiceImpl.java
- pom.xml
Besides title, lots of other changes:
1. Added Project Lombok dependency and removed almost all getters and setters from entities. Go to https://projectlombok.org for more information.
2. Changed all date generation code to match the same pattern.
3. Many other small fixes (removed all unused imports, fixed naming where needed, etc.).
> Khairulin create service dao controller for message entity 0.1

- mentionserver/src/main/java/com.mention/controller/ProfileController.java
- mentionserver/src/main/java/com.mention/dao/ProfileDao.java
- mentionserver/src/main/java/com.mention/model/Profile.java
- mentionserver/src/main/java/com.mention/model/User.java
- mentionserver/src/main/java/com.mention/service/ProfileService.java
- mentionserver/src/main/java/com.mention/service/ProfileServiceImpl.java
…in model 'Profile' and/or 'User'
> add user Profile entity, CRUD operation

- frontend/package.json
- frontend/src/components/Body.js
- frontend/src/components/Registration.js
- mentionserver/src/main/java/com.mention/beans/CreateUsers.java
- mentionserver/src/main/java/com.mention/controller/ChatController.java
- mentionserver/src/main/java/com.mention/controller/CommentController.java
- mentionserver/src/main/java/com.mention/controller/FavoriteController.java
- mentionserver/src/main/java/com.mention/controller/FollowController.java
- mentionserver/src/main/java/com.mention/controller/HelloMention.java
- mentionserver/src/main/java/com.mention/controller/LikeController.java
- mentionserver/src/main/java/com.mention/controller/MessageController.java
- mentionserver/src/main/java/com.mention/controller/PostController.java
- mentionserver/src/main/java/com.mention/controller/ProfileController.java
- mentionserver/src/main/java/com.mention/controller/UserController.java
- mentionserver/src/main/java/com.mention/model/User.java
Added simple user registration on front-end
> Khairulin user registration 0.1

- frontend/package-lock.json
- frontend/src/components/Feed.js
- frontend/src/containers/PostItem.js
- frontend/src/reducers/index.js
- frontend/src/store/index.js
- mentionserver/src/main/java/com.mention/beans/CreateUsers.java
- mentionserver/src/main/java/com.mention/controller/UserPostsController.java
- mentionserver/src/main/java/com.mention/dto/PostComment.java
- mentionserver/src/main/java/com.mention/dto/PostDto.java
- mentionserver/src/main/java/com.mention/dto/PostLike.java
- mentionserver/src/main/java/com.mention/dto/PostUserDetails.java
- mentionserver/src/main/java/com.mention/dto/ProfileAvatar.java
- mentionserver/src/main/java/com.mention/model/Profile.java
- mentionserver/src/main/java/com.mention/service/UserPostsService.java
- mentionserver/src/main/java/com.mention/service/UserPostsServiceImpl.java
1.Added 5 DTOs for Post(UserDto, PostDto, CommentDto, ProfileDto, LikeDto)
2.Added service and controller for viewing posts
3.Added more stuff to database to load on app startup
4.Other minor changes on back-end and front-end
5.Restored package-lock.json and added redux to package.json
> Added dtos for viewing posts, 1 service and 1 controller

- mentionserver/pom.xml
- mentionserver/src/test/java/com/mention/repository/MessageRepositoryTest.java
- pom.xml
move plugins from parent pom.xml to child pom.xml (mention-server back) for coveralls test coverage
> minor merge. Coveralls fix

- mentionserver/src/main/java/com.mention/controller/UserPostLikesController.java
- mentionserver/src/main/java/com.mention/dto/PostLikeRq.java
- mentionserver/src/main/java/com.mention/dto/UserDtoRq.java
- mentionserver/src/main/java/com.mention/service/PostLikeService.java
- mentionserver/src/main/java/com.mention/service/PostLikeServiceImpl.java
add PostLikeDtoRq  and implement method addPostLike
> upast : add PostLikeDtoRq + Service + Controller 0.6

- mentionserver/src/main/java/com.mention/controller/UserCommentLikeController.java
- mentionserver/src/main/java/com.mention/dto/CommentDtoIdRq.java
- mentionserver/src/main/java/com.mention/dto/CommentLikeDtoRq.java
- mentionserver/src/main/java/com.mention/repository/CommentLikeRepository.java
- mentionserver/src/main/java/com.mention/service/CommentLikeService.java
- mentionserver/src/main/java/com.mention/service/CommentLikeServiceImpl.java
- mentionserver/src/main/java/com.mention/service/PostLikeService.java
- mentionserver/src/main/java/com.mention/service/UserPostsService.java
- mentionserver/src/main/java/com.mention/service/UserPostsServiceImpl.java
+ add CommentLike
+ delete CommentLike
also add:
+ CommentDtoIdRq - Dto that return 'Id' of comment;
+ CommentLikeDtoRq - Dto get 'user' by 'UserDtoRq' and 'comment' by 'CommentDtoIdRq'
+ add Service and implementation 'CommentLikeServiceImpl' with methods add/delete CommentLike
+ add method deleteByUserIdAndCommentId to 'CommentLikeRepository'. That method used to check comment that need to delete
+ add Repository with methods add/delete
> upast: CommentLike functionality add/delete CommentLike 0.1.0

- frontend/src/containers/CommentContainer.js
- frontend/src/containers/CommentLikeItem.js
- frontend/src/containers/PostItem.js
- frontend/src/containers/PostLikeItem.js
- mentionserver/src/main/java/com.mention/dto/CommentDtoRs.java
- mentionserver/src/main/java/com.mention/service/CommentLikeServiceImpl.java
Added 1 container on front-end(CommentLikeItem) for displaying comment likes and fetching add/remove to back-end. Renamed LikeItem container to PostLikeitem. Fixes on back-end CommentLikesService.
> implemented adding/removing likes from comments functionality

- mentionserver/src/main/java/com.mention/controller/UserController.java
- mentionserver/src/main/java/com.mention/dto/CurrentUserDtoRs.java
- mentionserver/src/main/java/com.mention/dto/FollowDtoRs.java
- mentionserver/src/main/java/com.mention/service/UserService.java
- mentionserver/src/main/java/com.mention/service/UserServiceImpl.java
FollowDtoRs - return List followedUser;
in UserRepository add CurrentUserDtoRs getCurrentUser();
in UserController add -  @GetMapping("/current")
> add CurrentUserDtoRs for Current User

- mentionserver/pom.xml
- mentionserver/src/main/java/com.mention/beans/CreateUsers.java
- mentionserver/src/main/java/com.mention/beans/PasswordEncoderBean.java
- mentionserver/src/main/java/com.mention/config/SecurityConfigurer.java
- mentionserver/src/main/java/com.mention/config/SmartUserDetailsService.java
- mentionserver/src/main/java/com.mention/controller/FollowController.java
- mentionserver/src/main/java/com.mention/controller/LoginController.java
- mentionserver/src/main/java/com.mention/controller/UserController.java
- mentionserver/src/main/java/com.mention/controller/XController.java
- mentionserver/src/main/java/com.mention/controller/XLoginController.java
- mentionserver/src/main/java/com.mention/dto/CurrentUserDtoRs.java
- mentionserver/src/main/java/com.mention/dto/FollowDtoRq.java
- mentionserver/src/main/java/com.mention/dto/FollowDtoRs.java
- mentionserver/src/main/java/com.mention/model/User.java
- mentionserver/src/main/java/com.mention/repository/FollowRepository.java
- mentionserver/src/main/java/com.mention/repository/UserRepository.java
- mentionserver/src/main/java/com.mention/service/UserFollowService.java
- mentionserver/src/main/java/com.mention/service/UserFollowServiceImpl.java
- mentionserver/src/main/java/com.mention/service/UserService.java
- mentionserver/src/main/java/com.mention/service/UserServiceImpl.java
- mentionserver/src/main/resources/templates/login_.html
fix add/delete follow on back-end
> Upast: follow unfollow 1.0

- .gitignore
- frontend/src/components/Feed.js
- frontend/src/components/Navigation.js
- frontend/src/components/UserPage.js
- frontend/src/containers/LeftPanel.js
- mentionserver/src/main/java/com.mention/config/AmazonS3Configuration.java
- mentionserver/src/main/java/com.mention/service/UserPostsServiceImpl.java
> Hid the amazon keys in a file and added it to gitignore

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/Messages.js
- frontend/src/components/UserPage.js
- frontend/src/components/Websocket.js
- frontend/src/containers/Chat.js
- frontend/src/containers/FollowButton.js
- frontend/src/containers/UnffollowButton.js
- frontend/src/js/websocket.js
- mentionserver/src/main/java/com.mention/config/SecurityConfigurer.java
- mentionserver/src/main/java/com.mention/controller/NotificationController.java
- mentionserver/src/main/java/com.mention/dto/FollowDtoRs.java
- mentionserver/src/main/java/com.mention/model/Follow.java
- mentionserver/src/main/java/com.mention/service/UserServiceImpl.java
Small fixes on back-end were involved!
> Khairulin follow implementation front

- frontend/src/js/timestamp.js
Added file timestamp.js in frontend/js.
It will  show "Today" + time , "Yesterday" + time or earlier date in posts, comments, messadges.
> added file timestamp.js in front

- frontend/src/components/Registration.js
- frontend/src/components/UserPage.js
- mentionserver/src/main/java/com.mention/controller/ChatController.java
- mentionserver/src/main/java/com.mention/controller/CommentController.java
- mentionserver/src/main/java/com.mention/controller/CommentLikeController.java
- mentionserver/src/main/java/com.mention/controller/FollowController.java
- mentionserver/src/main/java/com.mention/controller/MessageController.java
- mentionserver/src/main/java/com.mention/controller/PostController.java
- mentionserver/src/main/java/com.mention/controller/PostLikeController.java
- mentionserver/src/main/java/com.mention/controller/ProfileController.java
- mentionserver/src/main/java/com.mention/controller/UserController.java
- mentionserver/src/main/java/com.mention/service/ChatService.java
- mentionserver/src/main/java/com.mention/service/ChatServiceImpl.java
- mentionserver/src/main/java/com.mention/service/CommentLikeService.java
- mentionserver/src/main/java/com.mention/service/CommentLikeServiceImpl.java
- mentionserver/src/main/java/com.mention/service/CommentService.java
- mentionserver/src/main/java/com.mention/service/CommentServiceImpl.java
- mentionserver/src/main/java/com.mention/service/FollowService.java
- mentionserver/src/main/java/com.mention/service/FollowServiceImpl.java
- mentionserver/src/main/java/com.mention/service/LoginServiceImpl.java
- mentionserver/src/main/java/com.mention/service/MessageService.java
- mentionserver/src/main/java/com.mention/service/MessageServiceImpl.java
- mentionserver/src/main/java/com.mention/service/PostLikeService.java
- mentionserver/src/main/java/com.mention/service/PostLikeServiceImpl.java
- mentionserver/src/main/java/com.mention/service/PostService.java
- mentionserver/src/main/java/com.mention/service/PostServiceImpl.java
- mentionserver/src/main/java/com.mention/service/ProfileService.java
- mentionserver/src/main/java/com.mention/service/ProfileServiceImpl.java
- mentionserver/src/main/java/com.mention/service/UserService.java
- mentionserver/src/main/java/com.mention/service/UserServiceImpl.java
1. Added checks to services to restrict current user from performing actions restricted to him. Example: now you can't use the token obtained from postman to delete/add/watch other people's messages, posts, comments, likes etc.
2. Added login and register validations with error messages handling on front-end and back-end.
3. Other minor changes.
> Added empty states, exceptions handling and access restrictions

- frontend/src/App.js
- frontend/src/components/Feed.js
- frontend/src/components/SearchPage.js
- frontend/src/components/UserPage.js
> Fixed scroll to top button functionality

- frontend/src/actions/commentsActions.js
- frontend/src/actions/postsActions.js
- frontend/src/components/Feed.js
- frontend/src/components/SearchPage.js
- frontend/src/components/UserPage.js
- frontend/src/containers/CommentContainer.js
- frontend/src/containers/PostItem.js
1. Now delete post/comment options are only visible for the post/comments authored by the currently logged in user. 
2. Added dom functionality to show "delete button" after click on the options. It gets hidden after you click on any other element on the page. 
3. Also added redux data load on deletion to show updated data after item gets deleted.
> show/hide post and comment delete buttons + fetch on delete

- frontend/src/components/Feed.js
- frontend/src/js/wsConnection.js
- mentionserver/src/main/java/com.mention/dto/FollowRs.java
- mentionserver/src/main/java/com.mention/dto/WsFeedRs.java
- mentionserver/src/main/java/com.mention/service/PostServiceImpl.java
Added websocket connection in feed to notify users about changes in their feed and make request for posts.
> Now feed refreshes dynamically

- frontend/package-lock.json
- frontend/src/components/UserPage.js
- frontend/src/containers/AddComment.js
- frontend/src/containers/HeaderPanel.js
- frontend/src/containers/PostItem.js
- frontend/src/scss/sections/post/_comment-container.scss
- frontend/src/scss/sections/post/_post-container.scss
- frontend/src/scss/sections/profile/_header-profile.scss
- frontend/src/scss/sections/profile/_profile-info.scss
1. Fixed UserPage (Post Items)
2. Added new animation on comments.
> Fixed UserPage

- frontend/src/components/Registration.js
- frontend/src/components/SearchPage.js
- frontend/src/containers/AddComment.js
- frontend/src/containers/SearchContainer.js
search form - works on enter and on button, min length of search input
> Orodiuk search form submit

- frontend/src/components/Messages.js
- frontend/src/components/Navigation.js
- frontend/src/components/SearchPage.js
- frontend/src/containers/EmptyState.js
- frontend/src/containers/HeaderPanel.js
- frontend/src/scss/modules/_empty-state.scss
Implemented timeout animation on EmptyState after 2.5 s
> Hryhoriev 0.1 timeout search
